backend:
  name: git-gateway
  branch: main # Branch to update
publish_mode: editorial_workflow
media_folder: 'public/images/uploads' # Media files will be stored in the repo under public/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads
site_url: https://cyberartbyjustin-beta.netlify.app/
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      # Home page
      - label: 'Homepage'
        name: 'homepage'
        indentifier_field: 'homepage'
        file: 'src/content/homepage.json'
        create: true
        extension: 'json'
        slug: 'home'
        preview_path: 'content/homepage.{{extension}}'
        fields:
          - label: 'Home GIF'
            name: 'home-gif'
            widget: 'object'
            fields:
              - { label: 'GIF Image', name: 'gif-image', widget: 'image' }
              - { label: 'GIF Alternate Text', name: 'gif-alt-text', widget: 'string' }
          - label: 'Welcome Text'
            name: 'welcome-text'
            widget: 'string'
          - label: 'To Gallery Button Text'
            name: 'to-gallery-button-text'
            widget: 'string'
      # Gallery page
      - label: 'Gallery'
        name: 'gallery'
        indentifier_field: 'gallery'
        file: src/content/gallery.json
        create: true
        extension: 'json'
        slug: 'gallery'
        fields:
          - label: 'Series'
            name: 'series'
            widget: 'list'
            fields:
              - { label: 'Series Name', name: 'series-name', widget: 'string' }
              - label: 'Artworks'
                name: 'artworks'
                widget: 'list'
                fields:
                  - { label: 'Artwork Name', name: 'artwork-name', widget: 'string' }
                  - { label: 'Artwork File', name: 'artwork-file', widget: 'image' }
      # About page
      - label: 'About'
        name: 'about'
        indentifier_field: 'about'
        file: 'src/content/about.json'
        create: true
        extension: 'json'
        slug: 'about'
        fields:
          - label: 'Profile Image'
            name: 'profile-image'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Alternate Text', name: 'alt-text', widget: 'string' }
          - label: 'Summary'
            name: 'summary'
            widget: 'object'
            fields:
              - { label: 'Summary Title', name: 'title', widget: 'string' }
              - { label: 'Summary Body', name: 'body', widget: 'text' }
          - label: 'CV'
            name: 'cv'
            widget: 'object'
            fields:
              - { label: 'Objective', name: 'objective', widget: 'text' }
              - { label: 'Education', name: 'education', widget: 'list' }
              - { label: 'Projects', name: 'projects', widget: 'list' }
          - label: 'Features'
            name: 'features'
            widget: 'list'
      # Contact page
      - label: 'Contact'
        name: 'contact'
        indentifier_field: 'contact'
        file: 'src/content/contact.json'
        create: true
        extension: 'json'
        slug: 'contact'
        fields:
          - label: 'Get In Touch'
            name: 'get-in-touch'
            widget: 'string'
          - label: 'Social Media Dialog'
            name: 'sm-dialog'
            widget: 'string'
      # Not Found page
      - label: 'Page Not Found'
        name: 'not-found'
        identifier_field: 'not-found'
        file: 'src/content/not-found.json'
        create: true
        extension: 'json'
        slug: 'not-found'
        fields:
          - label: 'Funny GIF'
            name: 'funny-gif'
            widget: 'image'
          - label: 'Funny Caption'
            name: 'funny-caption'
            widget: 'string'
          - label: 'Button Diaglog'
            name: 'button-dialog'
            widget: 'string'
      # Error Page
      - label: 'Error Occured'
        name: 'error-occured'
        identifier-field: 'error-occured'
        file: 'src/content/error-occured.json'
        create: true
        extension: 'json'
        slug: 'error-occured'
        fields:
          - label: 'Title'
            name: 'title'
            widget: 'string'
          - label: 'Subtitle'
            name: 'subtitle'
            widget: 'string'
          - label: 'Funny GIF'
            name: 'funny-gif'
            widget: 'image'
          - label: 'Funny Caption'
            name: 'funny-caption'
            widget: 'string'
