backend:
  name: git-gateway
  branch: main # Branch to update
publish_mode: editorial_workflow
media_folder: 'public/images/uploads' # Media files will be stored in the repo under public/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads
site_url: https://amazing-dubinsky-16c8e2.netlify.app/
extension: 'json'
collections:
  - label: 'About'
    name: 'about'
    folder: '_content/about'
    create: true
    fields:
      - label: 'CV'
        name: 'cv'
        fields:
          - label: 'Objective'
            name: 'objective'
            widget: 'text'
          - label: 'Education'
            name: 'education'
            widget: 'list'
            default: ['edu1']
            field:
              - { label: 'Edu', name: 'edu', widget: 'string' }
          - label: 'Projects'
            name: 'projects'
            widget: 'list'
            default: ['project1']
            field:
              - { label: 'Project', name: 'project', widget: 'string' }
      - label: 'Features'
        name: 'features'
        widget: 'list'
        default: ['feature1']
        field:
          - { label: 'Feature', name: 'feature', widget: 'string' }
