backend:
  name: git-gateway
  branch: main # Branch to update
publish_mode: editorial_workflow
media_folder: 'public/images/uploads' # Media files will be stored in the repo under public/images/uploads
public_folder: '/images/uploads' # The src attribute for uploaded media will begin with /images/uploads
site_url: https://amazing-dubinsky-16c8e2.netlify.app/
collections:
  - label: 'Pages'
    name: 'pages'
    files:
      # Home page
      - label: 'Homepage'
        name: 'homepage'
        indentifier_field: 'homepage'
        file: 'src/content/homepage.json'
        create: true
        extension: 'json'
        slug: 'home'
        preview_path: 'content/homepage.{{extension}}'
        fields:
          - label: 'Home GIF'
            name: 'home-gif'
            widget: 'object'
            fields:
              - { label: 'GIF Image', name: 'gif-image', widget: 'image' }
              - { label: 'GIF Alternate Text', name: 'gif-alt-text', widget: 'string' }
          - label: 'Welcome Text'
            name: 'welcome-text'
            widget: 'string'
          - label: 'To Gallery Button Text'
            name: 'to-gallery-button-text'
            widget: 'string'
      # About page
      - label: 'About'
        name: 'about'
        indentifier_field: 'about'
        file: 'src/content/about.json'
        create: true
        extension: 'json'
        slug: 'about'
        preview_path: 'content/aboutpage.{{extension}}'
        fields:
          - label: 'Profile Image'
            name: 'profile-image'
            widget: 'object'
            fields:
              - { label: 'Image', name: 'image', widget: 'image' }
              - { label: 'Alternate Text', name: 'alt-text', widget: 'string' }
          - label: 'Summary'
            name: 'summary'
            widget: 'object'
              - {label: 'Summary Title', name: 'title', widget: 'string'}
              - {label: 'Summary Body', name: 'body', widget: 'text'}
          - label: 'CV'
            name: 'cv'
            widget: 'object'
            fields:
              - { label: 'Objective', name: 'objective', widget: 'text' }
              - { label: 'Education', name: 'education', widget: 'list' }
              - { label: 'Projects', name: 'projects', widget: 'list' }
          - label: 'Features'
            name: 'features'
            widget: 'list'
      # Contact page
      - label: 'Contact'
        name: 'contact'
        indentifier_field: 'contact'
        file: 'src/content/contact.json'
        create: true
        extension: 'json'
        slug: 'contact'
        preview_path: 'content/contact.{{extension}}'
        fields:
          - label: 'Get In Touch'
            name: 'get-in-touch'
            widget: 'string'
          - label: 'Social Media Dialog'
            name: 'sm-dialog'
            widget: 'string'
