name: 'Cypress Tests'
on:
  push:
    branches: ['main', 'cypress']
  schedule:
    - cron: '0 0 * * *'
jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.0
      - run: npm install
      - run: npm run test:cy
